# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.cache/wt [current_project]
set_property parent.project_path /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/ip_repo/capteurDistanceUltrason_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/gainNvoies_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/melangeurNvoies_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/melangeur_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/filtre/src/FIR_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/FIR_RAM_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/PmodMIC3_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/pmod_audio_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/audio_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/codec_I2C_I2S_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/ip_repo/traitement_audio_1.0
  /home/nicolas/vivado/vivado/FPGA_xilinx/vivado-library-master
  /home/nicolas/vivado/vivado/FPGA_xilinx/IPs
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/constrs_1/new/contraintes.xdc
set_property used_in_implementation false [get_files /home/nicolas/vivado/vivado/FPGA_xilinx/vivado2019_2/project_1_vivado_2019_2/project_1_vivado_2019_1.srcs/constrs_1/new/contraintes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_5_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
