/*
 * xparameters.h
 *
 *  Created on: 3 avr. 2020
 *      Author: nicolas
 */

#ifndef XPARAMETERS_H_
#define XPARAMETERS_H_

#define XPAR_FIR_0_S00_AXI_BASEADDR 0
#define XPAR_FIR_1_S00_AXI_BASEADDR 0
#define XPAR_FIR_2_S00_AXI_BASEADDR 0
#define XPAR_FIR_3_S00_AXI_BASEADDR 0
#define XPAR_GAINNVOIES_0_S00_AXI_BASEADDR 0
#define XPAR_PMOD_AUDIO_0_S00_AXI_BASEADDR 0
#define XPAR_PMOD_AUDIO_1_S00_AXI_BASEADDR 0
#define XPAR_CAPTEURDISTANCEULTRA_0_S00_AXI_BASEADDR 0x43C70000

#endif /* XPARAMETERS_H_ */
